# Generated by Django 4.0.3 on 2022-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('order_items', models.CharField(max_length=10)),
            ],
        ),
    ]
